on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3
        sudo apt-get install -y libsqlite3-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Tests
      run: |
        python -m pytest

    - name: Run Ruff Check
      run: |
        ruff check .