[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fastlet"
version = "0.4.4"
requires-python = ">=3.13"
dependencies = [
    "crotal @ git+https://github.com/draew6/crotal.git",
    "pyopenapi-gen @ git+https://github.com/draew6/pyopenapi_gen.git",
    "typer[all]",
]

[project.optional-dependencies]
db = [
    "piping_bag @ git+https://github.com/draew6/piping_bag.git@0.6.3",
]

[project.scripts]
fastlet = "fastlet.cli:app"
